(map-mime-to-type "application/x-php" "cc.fooledit.editor.text.TextObjectType")
(map-suffix-to-mime "php" "application/x-php")
(map-suffix-to-mime "php3" "application/x-php")
(map-suffix-to-mime "php4" "application/x-php")
(map-suffix-to-mime "php5" "application/x-php")
(map-suffix-to-mime "phps" "application/x-php")
(mime-alias "application/x-php-source" "application/x-php")

(provide "application/x-php" "mode.php" "parser" "editor.text")
(provide "application/x-php" "mode.php" "highlighter" "editor.text")
