(import (java))
(invoke-static 'cc.fooledit.example.text.TextEditorModule 'onLoad)
(map-mime-to-type "application/x-awk" "text")
(map-mime-to-type "application/javascript" "text")
(map-mime-to-type "application/json" "text")
(map-mime-to-type "application/x-m4" "text")
(map-mime-to-type "application/x-perl" "text")
(map-mime-to-type "application/x-php" "text")
(map-mime-to-type "application/x-php-source" "text")
(map-mime-to-type "application/x-ruby" "text")
(map-mime-to-type "application/xml" "text")

