(map-mime-to-type "application/x-perl" "cc.fooledit.editor.text.TextObjectType")
(map-suffix-to-mime "pl" "application/x-perl")
(map-suffix-to-mime "pm" "application/x-perl")
(map-suffix-to-mime "pod" "application/x-perl")
(map-suffix-to-mime "t" "application/x-perl")
(map-suffix-to-mime "al" "application/x-perl")
(map-suffix-to-mime "perl" "application/x-perl")
(provide "application/x-perl" "mode.perl" "highlighter" "editor.text")
