(inform-jar "modules/editor.odf/dist/editor.odf.jar" "cc.fooledit.editor.odf.OdfModule" "onInstall")

(map-mime-to-type "application/vnd.oasis.opendocument.spreadsheet" "cc.fooledit.editor.odf.calc.OdsObjectType")
(map-suffix-to-mime "ods" "application/vnd.oasis.opendocument.spreadsheet")
(map-mime-to-type "application/vnd.oasis.opendocument.spreadsheet-template" "cc.fooledit.editor.odf.calc.OdsObjectType")
(map-suffix-to-mime "ots" "application/vnd.oasis.opendocument.spreadsheet-template")

(map-mime-to-type "application/vnd.oasis.opendocument.text" "cc.fooledit.editor.odf.writer.OdtObjectType")
(map-suffix-to-mime "odt" "application/vnd.oasis.opendocument.text")
(map-mime-to-type "application/vnd.oasis.opendocument.text-master" "cc.fooledit.editor.odf.writer.OdtObjectType")
(map-suffix-to-mime "odm" "application/vnd.oasis.opendocument.text-master")
(map-mime-to-type "application/vnd.oasis.opendocument.text-master-template" "cc.fooledit.editor.odf.writer.OdtObjectType")
(map-suffix-to-mime "otm" "application/vnd.oasis.opendocument.text-master-template")
(map-mime-to-type "application/vnd.oasis.opendocument.text-web" "cc.fooledit.editor.odf.writer.OdtObjectType")
(map-suffix-to-mime "oth" "application/vnd.oasis.opendocument.text-web")

(map-mime-to-type "application/vnd.oasis.opendocument.presentation" "cc.fooledit.editor.odf.impress.OdpObjectType")
(map-suffix-to-mime "odp" "application/vnd.oasis.opendocument.presentation")
(map-mime-to-type "application/vnd.oasis.opendocument.presentation-template" "cc.fooledit.editor.odf.impress.OdpObjectType")
(map-suffix-to-mime "otp" "application/vnd.oasis.opendocument.presentation-template")

(map-mime-to-type "application/vnd.oasis.opendocument.graphics" "cc.fooledit.editor.odf.draw.OdgObjectType")
(map-suffix-to-mime "odg" "application/vnd.oasis.opendocument.graphics")
(map-mime-to-type "application/vnd.oasis.opendocument.graphics-template" "cc.fooledit.editor.odf.draw.OdgObjectType")
(map-suffix-to-mime "otg" "application/vnd.oasis.opendocument.graphics-template")
(map-mime-to-type "application/vnd.oasis.opendocument.image" "cc.fooledit.editor.odf.draw.OdgObjectType")
(map-suffix-to-mime "odi" "application/vnd.oasis.opendocument.image")

(map-mime-to-type "application/vnd.oasis.opendocument.chart" "cc.fooledit.editor.odf.chart.ChartObjectType")
(map-suffix-to-mime "odc" "application/vnd.oasis.opendocument.chart")
(map-mime-to-type "application/vnd.oasis.opendocument.chart-template" "cc.fooledit.editor.odf.chart.ChartObjectType")
(map-suffix-to-mime "otc" "application/vnd.oasis.opendocument.chart-template")
