(import (java))
(invoke-static 'cc.fooledit.editor.image.ImageModule 'onInstall)
(map-mime-to-type "image/bmp" "cc.fooledit.editor.image.GraphicsObjectType")
(map-mime-to-type "image/gif" "cc.fooledit.editor.image.GraphicsObjectType")
(map-mime-to-type "image/jpeg" "cc.fooledit.editor.image.GraphicsObjectType")
(map-mime-to-type "image/png" "cc.fooledit.editor.image.GraphicsObjectType")
(map-suffix-to-mime "bmp" "image/bmp")
(map-suffix-to-mime "dib" "image/bmp")
(map-suffix-to-mime "gif" "image/gif")
(map-suffix-to-mime "jpeg" "image/jpeg")
(map-suffix-to-mime "jpg" "image/jpeg")
(map-suffix-to-mime "jpe" "image/jpeg")
(map-suffix-to-mime "png" "image/png")
(mime-alias "image/x-bmp" "image/bmp")
(mime-alias "image/x-MS-bmp" "image/bmp")
(mime-alias "image/pjpeg" "image/jpeg")

