(import (java))
(invoke-static 'cc.fooledit.editor.zip.ZipModule 'onLoad)
(map-mime-to-type "application/x-7z-compressed" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-archive" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-arj" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-bzip" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/x-bzip2" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/x-cpio" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-gtar" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/gzip" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/x-gzip" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/java-archive" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-java-archive" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-jar" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-java-pack200" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/x-lz4" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/x-lzma" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/x-tar" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-xz" "cc.fooledit.editor.zip.ZipObjectType")
(map-mime-to-type "application/zip" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/x-zip-compressed" "cc.fooledit.editor.zip.ArchiveObjectType")
(map-mime-to-type "application/zlib" "cc.fooledit.editor.zip.ZipObjectType")

;TODO: DUMP,Brotli,DEFLATE,LZ77,LZW,Snappy