(import (java))
(invoke-static 'cc.fooledit.core.CoreModule 'onLoad)
(let ((types (get-registry "core/provider/core/data_object_type")))
)
(let ((editors (get-registry "core/provider/core/data_object_editor")))
)
(let ((apps (get-registry "core/provider/core/application")))
(let ((mimes (get-registry "core/provider/core/content_type_loader")))
(let ((commands (get-registry "core/provider/core/command")))
(let ((protocols (get-registry "core/provider/core/protocol")))
     )
(let ((templates (get-registry "core/provider/core/template_type")))
)
(let ((provider (get-registry "core/provider/")))
     (get-or-create-registry provider "core/provider")
     (get-or-create-registry provider "core/template")
     (get-or-create-registry provider "core/content_type_alias")
     (get-or-create-registry provider "core/content_type_superclass")
     (get-or-create-registry provider "core/suffix"))
