title: 傻瓜编辑器
description: 全心全意为傻瓜服务
lang: zh-CN
author: 陈颂光
google_analytics: 
show_downloads: false
paginate: 20
baseurl: ""
permalink: none

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

markdown: kramdown
exclude: ["README.md"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
