source 'https://rubygems.org'
#gem 'github-pages', group: :jekyll_plugins

#gemspec
ruby RUBY_VERSION

# This will help ensure the proper Jekyll version is running.
gem "jekyll"
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-redirect-from'
